server:
  port: 9090

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
spring:  application:    name: zuul_user_service
  redis:    host: localhost
    port: 6379
    database: 1
    password: 
    jedis:      pool:        max-active: 10
        max-idle: 10
        max-wait: 30
        min-idle: 10
feign:  hystrix:    enabled: true #开启熔断器功能
zuul:
  prefix: /api
  routes:
    client1:
      path: /client1/**
      sensitive-headers:
      - 
      service-id: client1_service